cacheFolder: ./.yarn/cache

enableGlobalCache: false

enableTelemetry: false

nodeLinker: node-modules

# npmScopes:
#  default:
#    npmAlwaysAuth: true
#    npmRegistryServer: "https://npm.pkg.github.com/"

preferInteractive: true

yarnPath: .yarn/releases/yarn-4.9.2.cjs
